# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabnoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vocabnoteapp.User'),
            preserve_default=False,
        ),
    ]
