# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabnoteapp', '0003_auto_20171023_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
    ]
