# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabnoteapp', '0005_auto_20171102_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
    ]
