# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabnoteapp', '0008_auto_20171127_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.AddField(
            model_name='user',
            name='Age',
            field=models.IntegerField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='User_Auth_ID',
            field=models.IntegerField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='User',
            field=models.ManyToManyField(related_name='WordList', to='vocabnoteapp.User'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set([]),
        ),
    ]
