# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabnoteapp', '0010_auto_20171128_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
