# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabnoteapp', '0012_user_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classification', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='Classification',
        ),
        migrations.RemoveField(
            model_name='word',
            name='User',
        ),
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Auth_ID',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='classification',
            name='User',
            field=models.ManyToManyField(related_name='ClassList', to='vocabnoteapp.User'),
        ),
        migrations.AddField(
            model_name='word',
            name='Class_Name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabnoteapp.Classification'),
            preserve_default=False,
        ),
    ]
