# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabnoteapp', '0013_auto_20171128_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='User',
            field=models.ManyToManyField(related_name='Classification', to='vocabnoteapp.User'),
        ),
        migrations.AlterField(
            model_name='word',
            name='Class_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Word', to='vocabnoteapp.Classification'),
        ),
    ]
