# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabnoteapp', '0017_auto_20171128_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='User',
            field=models.ManyToManyField(related_name='Classification', to='vocabnoteapp.User'),
        ),
    ]
